language: java
jdk:
  - oraclejdk8
services:
  - mysql
before_script:
  - mysql -e 'DROP DATABASE IF EXISTS ponto_inteligente'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ponto_inteligente'
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)